spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:firebirdsql://localhost:3050//firebird/data/delivery.fdb?encoding=UTF8
    username: sysdba
    password: masterkey
    driver-class-name: org.firebirdsql.jdbc.FBDriver

spring-doc:
  swagger-ui:
    path: /
    tagsSorter: alpha
    operationsSorter: method

jwt:
  expiration: 43200000
  secret: delivery123
